### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by CraigThomasson** [CraigThomasson/Does_It_-Vegan#2]
As a **vegan** i can **search for vegan restaurants** so that ** can easily find somewhere to eat **.

# Acceptance Criteria:
* Acceptance Criteria 1: user must be able to search for restaurants
* Acceptance Criteria 2: user must be able to see the restaurant location
* Acceptance Criteria 3: user must see that the restaurant offers vegan options

# Tasks
- [ ] Task 1: add a search bar to the home page
- [ ] Task 2 add restaurant cards to home page on search
- [ ] Task 3 add location details to restaurant cards
- [ ] Task 4 add details button to restaurant cards
