### ISSUE TITLE
USER STORY <leave reviews>

### ISSUE THREAD

**Issue by CraigThomasson** [CraigThomasson/Does_It_-Vegan#3]
As a **diner** I can **leave a review of the restaurant so that** **other diners can see the quality of the service **.

# Acceptance Criteria:
* diners can find the restaurant they have dined at:
* leave a review of the restaurant:
* Edit and delete their review:

# Tasks
- [ ] Task 1: add search bar to restaurant view
- [ ] Task 2 add review section to restaurant view
- [ ] Task 3 add edit and delete options to users reviews
