### ISSUE TITLE
USER STORY <create user acount>

### ISSUE THREAD

**Issue by CraigThomasson** [CraigThomasson/Does_It_-Vegan#4]
As a **user** I can **create an account** so that **I can leave reviews and add to the site**.

# Acceptance Criteria:
* Acceptance Criteria 1: user can create a unique user account
* Acceptance Criteria 2: user can edit their account
* Acceptance Criteria 3: user can sign in and out of the account

# Tasks
- [ ] Task 1: add signe in option to main page
- [ ] Task 2 create signe up form
- [ ] Task 3 vreate view for signe up form
